# This is a basic workflow that is manually triggered

name: Build with WDK

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install WDK
      run: choco install windowsdriverkit11
    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
        dir "C:\Program Files (x86)\Windows Kits"
        dir "C:\Program Files (x86)\Windows Kits\10"
        dir "C:\Program Files (x86)\Windows Kits\10\bin"
        dir "C:\Program Files (x86)\Windows Kits\11"
        dir "C:\Program Files (x86)\Windows Kits\11\bin"
        
